# Generated by Django 3.0.7 on 2020-06-13 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 13, 11, 38, 45, 688048, tzinfo=utc)),
        ),
    ]
