# Generated by Django 3.0.7 on 2020-06-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20200608_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='phone',
            field=models.CharField(default='555-555-5555', max_length=20),
            preserve_default=False,
        ),
    ]
