# Generated by Django 3.0.7 on 2020-06-09 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
