# Generated by Django 3.0.7 on 2020-06-13 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20200609_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 13, 11, 38, 45, 634706, tzinfo=utc)),
        ),
    ]
